import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "en" | "de" | "fr" | "es" | "ja" | "ml" | "hi" | "ar";

export interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ml", name: "മലയാളം", flag: "🇮🇳" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "ar", name: "العربية", flag: "🇦🇪" },
];

const translations = {
  en: {
    nav: {
      threats: "Threat Landscape",
      howItWorks: "How It Works",
      modules: "Platform Modules",
      playground: "Playground Center",
      ecosystem: "Ecosystem Topology",
      ledger: "Accuracy Ledger",
      tunnel: "Secure Tunnel",
      launch: "Launch Trust Scan",
      shLine: "by Shaduli"
    },
    hero: {
      securing: "AIVERSE SECURING GLOBAL DIGITAL AUTHENTICITY",
      titlePre: "Building Trust ",
      titleSpan: "In The AI Era.",
      subtitle: "AiVerse detects harmful AI-generated content, identifies cyber threats, and verifies digital authenticity for governments and global enterprises.",
      ctasScan: "Launch Trust Scan",
      ctasDemo: "Watch Demo",
      monitoring: "⚠️ MONITORING ACTIVE: SECURING 4.8M ADVERSARIAL CHANNELS TODAY",
      threatIntel: "Threat Intelligence",
      monitoringActive: "Global monitoring active",
      deepfakeDet: "Deepfake Detected",
      deepfakeDetMsg: "Media source identified as synthetic AI generation.",
      justNow: "Just now • North America",
      voiceAnomaly: "Voice Anomaly",
      voiceAnomalyMsg: "Verification failed: Synthetic biometric signature.",
      twoMAgo: "2m ago • European Union",
      originVerified: "Origin Verified",
      originVerifiedMsg: "Source tracing complete: Authentic digital asset.",
      fiveMAgo: "5m ago • Asia-Pacific",
      trustScore: "Trust Score Index",
      scannedContent: "Total Scanned Content",
      scannedSub: "Realtime verified objects",
      threatsIsolated: "AI Threats Isolated",
      threatsSub: "Deepfakes blocked at gates",
      accuracyVector: "Accuracy Vector",
      accuracySub: "Tuned forensic confidence",
      enterpriseCovered: "Enterprise Orgs Covered",
      enterpriseSub: "Governments & bank registries",
    },
    scanModal: {
      decentralized: "AIVERSE DECENTRALIZED SCAN ENGINE",
      title: "Secure Trust Diagnostic Workspace",
      subtitle: "Secure sandbox payload ingestion. Paste social URLs, email bodies, file hashes, or click simulator triggers to review digital authenticity reports.",
      imgBtn: "📸 Image (.jpg)",
      voiceBtn: "🎙️ Voice Speech",
      videoBtn: "🎥 Video Deepfake",
      emailBtn: "📩 Phish Email",
      inputParams: "Input Payload Parameters",
      secureActive: "SECURE TUNNEL ACTIVE",
      dragDrop: "Drag-and-drop secure file attachment or browser logs directory",
      dragSub: "PDF, WAV, PNG, MP4 support. Encrypted, SOC2-Sandbox private logs.",
      ingestBtn: "SECURE INGEST & ANALYZE PAYLOAD",
      stage1: "STAGE 1/2: PIXEL SEAMS CHECK",
      stage2: "STAGE 2/2: CALCULATING SIGNATURE COHERENCE",
      criticalTitle: "DIAGNOSTIC CRITICAL",
      authScore: "Authenticity Score",
      lowScore: "(LOW)",
      classification: "Classification",
      legalAdmissible: "Legal Admissible",
      certificate: "Trace Verified Certificate",
      outputTitle: "AI Forensics Output:",
      outputMsg: "GAN grid artifact mismatch. Speech phonetic compression do not match physical human voice profiles. Security actions logged in the corporate boundary ledger.",
      ingestNext: "Ingest Next Sample",
      closeWorkspace: "Close Workspace"
    },
    threats: {
      category: "Section 02 // Generative Risks",
      title: "The AI Threat Landscape",
      subtitle: "Synthetic materials are reaching human-grade fidelity. Review the primary attack vectors currently weaponized by cyber criminals.",
      reconnaissance: "AIVERSE THREAT RECONNAISSANCE",
      activeInspect: "Active Inspect",
      inactiveInspect: "Inspect Vector",
      deepNoiseMatch: "IMAGE DEEP NOISE MATCH:",
      latentArtifacts: "SUSPECTED LATENT ARTIFACTS",
      dragSlider: "DRAG IN PREVIEW TO INSPECT",
      ganArtifacts: "GAN Seam Failures Found",
      pixelInconsistencies: "Isolated pixel mesh inconsistencies on skin margins",
      cleanOriginal: "CLEAN ORIGINAL METADATA",
      verifiedRaw: "Verified Raw Camera sensor record intact",
    },
    workflow: {
      category: "Section 03 // Pipeline Forensic",
      title: "How AiVerse Works",
      subtitle: "Our multi-model parallel scanner decodes digital DNA layer-by-layer. Experience the real-time parsing sequence.",
      auditEngine: "AIVERSE AUDIT ENGINE v4.21",
      sandboxTitle: "Interactive Forensic Scanning Sandbox",
      sandboxSub: "Select a sample digital asset payload below to trigger the actual timeline scan. Watch each algorithm deploy.",
      scanRunning: "Forensics Running",
      resetEcosystem: "Reset Ecosystem",
      secureIngest: "Secure Ingest & Run",
      consoleTitle: "SCAN TELEMETRY SHIELD CONSOLE",
      consoleSub: "TIMESTAMP: 2026-06-06 UTC",
      terminalIdleSubtitle: "Select payload and choose \"Secure Ingest & Run\" to initiate parallel AI Trust checks.",
      processingStage: "[PROCESSING STAGE ... COMMENCING NEURAL HASHING PATTERNS]"
    },
    modules: {
      category: "Section 04 // Product Showcase",
      title: "Platform Modules",
      subtitle: "Sovereign trust verticals engineered for corporate communications, identity defense, and media security.",
      kpiLabel: "KPI Target",
    },
    demo: {
      category: "Sections 05–13 // Diagnostic Lab",
      title: "Interactive Diagnostic Center",
      subtitle: "Simulate deepfake detection, audio spectrograms, trace maps, and cyber filters in active SaaS environments.",
      orgsCovered: "ENTERPRISES COVERED",
      orgsVal: "4,800 orgs",
    },
    ecosystem: {
      nodeSelected: "Currently Selected Node: ",
      brainTitle: "AiVerse ONE",
      brainSub: "Unifying Brain",
    },
    metrics: {
      category: "SUCCESS AUDIT RECORDINGS",
      caseStudies: "Continuous Performance Evaluation",
      caseSubtitle: "We benchmark our parallel models against international forensic standards Daily.",
      avgAccuracy: "98.7% Avg",
      avgAccuracyTag: "Pixel Accuracy",
      latentDelay: "Latent Delay",
      restartBtn: "Restart Simulation",
    },
    footer: {
      brandDesc: "Making AI Accountable, Traceable, and Trustworthy. The premium governance platform trusted by global organizations, banks, brand managers, and public sectors.",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "Zurich Old City, Switzerland",
      endpointLease: "SECURE ENDPOINT LEASE",
      products: "Products",
      solutions: "Solutions",
      company: "Company",
      contactHeader: "Contact Desk",
    }
  },
  de: {
    nav: {
      threats: "Bedrohungslage",
      howItWorks: "Funktionsweise",
      modules: "Plattformmodule",
      playground: "Prüfzentrum",
      ecosystem: "Ökosystem",
      ledger: "Genauigkeitsregister",
      tunnel: "Sicherer Tunnel",
      launch: "Vertrauensscan starten",
      shLine: "von Shaduli"
    },
    hero: {
      securing: "AIVERSE SICHERT GLOBALE DIGITALE AUTHENTIZITÄT",
      titlePre: "Vertrauen schaffen ",
      titleSpan: "im KI-Zeitalter.",
      subtitle: "AiVerse erkennt schädliche KI-generierte Inhalte, identifiziert Cyber-Bedrohungen und verifiziert digitale Authentizität für Regierungen und globale Unternehmen.",
      ctasScan: "Vertrauensscan starten",
      ctasDemo: "Demo ansehen",
      monitoring: "⚠️ ÜBERWACHUNG AKTIV: 4,8 MIO. ADVERSARIELLE KANÄLE GESICHERT",
      threatIntel: "Bedrohungsanalyse",
      monitoringActive: "Globale Überwachung aktiv",
      deepfakeDet: "Deepfake erkannt",
      deepfakeDetMsg: "Medienquelle als synthetische KI-Generierung identifiziert.",
      justNow: "Gerade eben • Nordamerika",
      voiceAnomaly: "Sprachanomalie",
      voiceAnomalyMsg: "Verifizierung fehlgeschlagen: Synthetische biometrische Signatur.",
      twoMAgo: "Vor 2 Min. • Europäische Union",
      originVerified: "Herkunft verifiziert",
      originVerifiedMsg: "Quellenrückverfolgung abgeschlossen: Authentisches Medium.",
      fiveMAgo: "Vor 5 Min. • Asien-Pazifik",
      trustScore: "Vertrauens-Score-Index",
      scannedContent: "Gescanne Inhalte gesamt",
      scannedSub: "Echtzeit-verifizierte Objekte",
      threatsIsolated: "KI-Bedrohungen isoliert",
      threatsSub: "Deepfakes an den Toren blockiert",
      accuracyVector: "Genauigkeitsvektor",
      accuracySub: "Optimiertes forensisches Vertrauen",
      enterpriseCovered: "Abgedeckte Unternehmen",
      enterpriseSub: "Regierungs- & Bankregister",
    },
    scanModal: {
      decentralized: "AIVERSE DEZENTRALISIERTE SCAN-ENGINE",
      title: "Sicherer Vertrauensdiagnose-Arbeitsbereich",
      subtitle: "Sichere Sandbox-Nutzdatenaufnahme. Fügen Sie Social-Media-URLs, E-Mail-Texte oder Datei-Hashes ein, um Authentizitätsberichte anzuzeigen.",
      imgBtn: "📸 Bild (.jpg)",
      voiceBtn: "🎙️ Stimme / Sprache",
      videoBtn: "🎥 Video-Deepfake",
      emailBtn: "📩 Phishing-E-Mail",
      inputParams: "Eingabeparameter für Nutzdaten",
      secureActive: "SICHERER TUNNEL AKTIV",
      dragDrop: "Dateien hier ablegen oder Protokollverzeichnis durchsuchen",
      dragSub: "Unterstützt PDF, WAV, PNG, MP4. Verschlüsselte, private SOC2-Protokolle.",
      ingestBtn: "DATEN SICHER AUFNEHMEN & ANALYSIEREN",
      stage1: "STUFE 1/2: PIXELNAHT-PRÜFUNG",
      stage2: "STUFE 2/2: SIGNATURKOHÄRENZ-BERECHNUNG",
      criticalTitle: "DIAGNOSE KRITISCH",
      authScore: "Authentizitäts-Score",
      lowScore: "(NIEDRIG)",
      classification: "Klassifizierung",
      legalAdmissible: "Gerichtlich verwertbar",
      certificate: "Rückverfolgbares Zertifikat",
      outputTitle: "KI-Forensik-Ergebnis:",
      outputMsg: "GAN-Gitter-Artefakt-Abweichung. Phonetische Sprachkompression entspricht nicht dem menschlichen Profil. Sicherheitsmaßnahmen im Register protokolliert.",
      ingestNext: "Nächste Probe aufnehmen",
      closeWorkspace: "Arbeitsbereich schließen"
    },
    threats: {
      category: "Abschnitt 02 // Generative Risiken",
      title: "Die KI-Bedrohungslage",
      subtitle: "Synthetische Medien erreichen menschliche Qualität. Überprüfen Sie die von Cyberkriminellen genutzten Hauptangriffsvektoren.",
      reconnaissance: "AIVERSE BEDROHUNGSAUFKLÄRUNG",
      activeInspect: "Aktive Prüfung",
      inactiveInspect: "Vektor prüfen",
      deepNoiseMatch: "BILD-TIEFENRAUSCH-ABGLEICH:",
      latentArtifacts: "VERMUTETE LATENTE ARTEFAKTE",
      dragSlider: "ZUM PRÜFEN IM VORSCHAUFENSTER ZIEHEN",
      ganArtifacts: "GAN-Nahtfehler gefunden",
      pixelInconsistencies: "Inkonsistenzen im Pixelnetz an den Hauträndern isoliert",
      cleanOriginal: "SAUBERE ORIGINAL-METADATEN",
      verifiedRaw: "Verifizierter Rohkamerasensor-Eintrag intakt",
    },
    workflow: {
      category: "Abschnitt 03 // Forensische Pipeline",
      title: "Wie AiVerse funktioniert",
      subtitle: "Unser paralleler Multi-Modell-Scanner entschlüsselt die digitale DNA Schicht für Schicht. Erleben Sie die Sequenz.",
      auditEngine: "AIVERSE PRÜF-ENGINE v4.21",
      sandboxTitle: "Interaktive forensische Scan-Sandbox",
      sandboxSub: "Wählen Sie unten eine Mediendatei aus, um den Timeline-Scan auszulösen. Beobachten Sie die Algorithmen.",
      scanRunning: "Forensik läuft",
      resetEcosystem: "System zurücksetzen",
      secureIngest: "Sicher aufnehmen & ausführen",
      consoleTitle: "TELEMETRIE-KONSOLE",
      consoleSub: "ZEITSTEMPEL: 2026-06-06 UTC",
      terminalIdleSubtitle: "Wählen Sie ein Medium und klicken Sie auf \"Sicher aufnehmen & ausführen\", um die Prüfungen zu starten.",
      processingStage: "[VERARBEITUNGSLAGE ... NEURALE HASH-MUSTER WERDEN GESTARTET]"
    },
    modules: {
      category: "Abschnitt 04 // Produktübersicht",
      title: "Plattformmodule",
      subtitle: "Souveräne Vertrauenslösungen für Unternehmenskommunikation, Identitätsschutz und Mediensicherheit.",
      kpiLabel: "KPI-Ziel",
    },
    demo: {
      category: "Abschnitte 05–13 // Diagnoselabor",
      title: "Interaktives Diagnosezentrum",
      subtitle: "Simulieren Sie Deepfake-Erkennung, Audiospektrogramme, Spurenkarten und Cyber-Filter in einer aktiven SaaS-Umgebung.",
      orgsCovered: "ABGEDECKTE KLIENTEN",
      orgsVal: "4.800 Organisationen",
    },
    ecosystem: {
      nodeSelected: "Aktuell ausgewählter Knoten: ",
      brainTitle: "AiVerse ONE",
      brainSub: "Vereinigendes Gehirn",
    },
    metrics: {
      category: "ERFOLGREICHE PRÜFAUFZEICHNUNGEN",
      caseStudies: "Kontinuierliche Leistungsbewertung",
      caseSubtitle: "Wir vergleichen unsere parallelen Modelle täglich mit internationalen forensischen Standards.",
      avgAccuracy: "98.7% Schnitt",
      avgAccuracyTag: "Pixel-Genauigkeit",
      latentDelay: "Latente Verzögerung",
      restartBtn: "Simulation neu starten",
    },
    footer: {
      brandDesc: "KI rechenschaftspflichtig, rückverfolgbar und vertrauenswürdig machen. Die Premium-Governance-Plattform für Regierungen, Banken und globale Marken.",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "Zürcher Altstadt, Schweiz",
      endpointLease: "SECURE ENDPOINT LEASE",
      products: "Produkte",
      solutions: "Lösungen",
      company: "Unternehmen",
      contactHeader: "Kontakt-Desk",
    }
  },
  fr: {
    nav: {
      threats: "Menaces",
      howItWorks: "Fonctionnement",
      modules: "Modules",
      playground: "Lab d'Essai",
      ecosystem: "Écosystème",
      ledger: "Registre de Précision",
      tunnel: "Tunnel Sécurisé",
      launch: "Lancer le Scan",
      shLine: "par Shaduli"
    },
    hero: {
      securing: "AIVERSE SÉCURISE L'AUTHENTICITÉ NUMÉRIQUE GLOBALE",
      titlePre: "Bâtir la Confiance ",
      titleSpan: "à l'Ère de l'IA.",
      subtitle: "AiVerse détecte les contenus synthétiques malveillants, identifie les cyber-menaces et certifie l'authenticité numérique pour les gouvernements et entreprises.",
      ctasScan: "Lancer le Scan",
      ctasDemo: "Voir la Démo",
      monitoring: "⚠️ SURVEILLANCE ACTIVE : 4.8M DE CANAUX ADVERSES SÉCURISÉS AUJOURD'HUI",
      threatIntel: "Renseignement de Menace",
      monitoringActive: "Surveillance globale active",
      deepfakeDet: "Deepfake Détecté",
      deepfakeDetMsg: "Source identifiée comme une génération IA synthétique.",
      justNow: "À l'instant • Amérique du Nord",
      voiceAnomaly: "Anomalie Vocale",
      voiceAnomalyMsg: "Échec de vérification : Signature biométrique synthétique.",
      twoMAgo: "Il y a 2m • Union Européenne",
      originVerified: "Origine Vérifiée",
      originVerifiedMsg: "Traçabilité terminée : Actif numérique authentique.",
      fiveMAgo: "Il y a 5m • Asie-Pacifique",
      trustScore: "Indice de Score de Confiance",
      scannedContent: "Contenu Total Scanné",
      scannedSub: "Objets vérifiés en temps réel",
      threatsIsolated: "Menaces IA Isolées",
      threatsSub: "Deepfakes bloqués aux barrières",
      accuracyVector: "Vecteur de Précision",
      accuracySub: "Confiance forensique calibrée",
      enterpriseCovered: "Entreprises Couvertes",
      enterpriseSub: "Gouvernements & registres bancaires",
    },
    scanModal: {
      decentralized: "MOTEUR DE SCAN DÉCENTRALISÉ AIVERSE",
      title: "Espace de Diagnostic de Confiance Sécurisé",
      subtitle: "Ingestion sécurisée dans un bac à sable. Collez des URL, des e-mails, ou des hachages de fichiers pour obtenir un rapport de certification.",
      imgBtn: "📸 Image (.jpg)",
      voiceBtn: "🎙️ Voix / Parole",
      videoBtn: "🎥 Deepfake Vidéo",
      emailBtn: "📩 E-mail Phishing",
      inputParams: "Paramètres de flux d'entrée",
      secureActive: "TUNNEL SÉCURISÉ ACTIF",
      dragDrop: "Glissez-déposez le fichier ou parcourez le répertoire",
      dragSub: "Supporte PDF, WAV, PNG, MP4. Journaux sécurisés SOC2 privés.",
      ingestBtn: "INGÉRER & ANALYSER LE FLUX SÉCURISÉ",
      stage1: "ÉTAPE 1/2 : VÉRIFICATION DES SOUDURES PIXEL",
      stage2: "ÉTAPE 2/2 : CALCUL DE LA COHÉRENCE DE SIGNATURE",
      criticalTitle: "DIAGNOSTIC CRITIQUE",
      authScore: "Score d'Authenticité",
      lowScore: "(FAIBLE)",
      classification: "Classification",
      legalAdmissible: "Admissible Légalement",
      certificate: "Certificat de Traçabilité Validé",
      outputTitle: "Résultats Forensiques :",
      outputMsg: "Écart de grille de pixels GAN. Les caractéristiques phonétiques de la voix ne correspondent pas au profil humain. Actions consignées.",
      ingestNext: "Ingérer un autre échantillon",
      closeWorkspace: "Fermer l'espace"
    },
    threats: {
      category: "Section 02 // Risques Génératifs",
      title: "Le Paysage des Menaces IA",
      subtitle: "Les contenus synthétiques atteignent une fidélité humaine. Analysez les principaux vecteurs d'attaque aujourd'hui.",
      reconnaissance: "RECONNAISSANCE DES MENACES AIVERSE",
      activeInspect: "Inspection Active",
      inactiveInspect: "Inspecter le Vecteur",
      deepNoiseMatch: "CONCORDANCE DE BRUIT IMAGE :",
      latentArtifacts: "ARTEFACTS LATENTS SUSPECTÉS",
      dragSlider: "GLISSER DANS L'APERÇU POUR INSPECTER",
      ganArtifacts: "Défauts de soudure GAN détectés",
      pixelInconsistencies: "Incohérences de maillage isolées sur les contours cutanés",
      cleanOriginal: "MÉTADONNÉES D'ORIGINE PROPRES",
      verifiedRaw: "Historique de capteur d'appareil d'origine intact",
    },
    workflow: {
      category: "Section 03 // Pipeline Forensique",
      title: "Comment fonctionne AiVerse",
      subtitle: "Notre scanner multi-modèle parallèle décode l'ADN numérique couche par couche. Observez la séquence.",
      auditEngine: "MOTEUR D'AUDIT AIVERSE v4.21",
      sandboxTitle: "Bac à sable Interactif de Scan Forensique",
      sandboxSub: "Sélectionnez un échantillon ci-dessous pour lancer le scan. Observez le déploiement des algorithmes.",
      scanRunning: "Analyse en cours",
      resetEcosystem: "Réinitialiser",
      secureIngest: "Ingérer & Lancer",
      consoleTitle: "CONSOLE DE TÉLÉMÉTRIE SHIELD",
      consoleSub: "TIMESTAMP : 2026-06-06 UTC",
      terminalIdleSubtitle: "Sélectionnez un flux et cliquez sur \"Ingérer & Lancer\" pour initier les analyses de confiance.",
      processingStage: "[PHASE DE TRAITEMENT ... MISE EN ROUTE DES EMPREINTES NEURALES]"
    },
    modules: {
      category: "Section 04 // Modules Plateforme",
      title: "Modules Applicatifs",
      subtitle: "Solutions de confiance souveraines conçues pour la communication d'entreprise, la défense d'identité et la sécurité média.",
      kpiLabel: "Cible KPI",
    },
    demo: {
      category: "Sections 05–13 // Laboratoire",
      title: "Centre de Diagnostic Interactif",
      subtitle: "Simulez la détection de deepfakes, spectrogrammes vocaux, cartes d'origine et filtres cyber.",
      orgsCovered: "ENTREPRISES SÉCURISÉES",
      orgsVal: "4,800 orgs",
    },
    ecosystem: {
      nodeSelected: "Noeud actuellement sélectionné : ",
      brainTitle: "AiVerse ONE",
      brainSub: "Cerveau Unifié",
    },
    metrics: {
      category: "ENREGISTREMENTS BANCAIRES VERIFIÉS",
      caseStudies: "Évaluation de Performance Continue",
      caseSubtitle: "Nous mesurons quotidiennement nos performances par rapport aux standards scientifiques internationaux.",
      avgAccuracy: "98.7% Moy.",
      avgAccuracyTag: "Précision Pixel",
      latentDelay: "Délai Latent",
      restartBtn: "Relancer la simulation",
    },
    footer: {
      brandDesc: "Rendre l'IA responsable, traçable et digne de confiance. La plateforme de gouvernance premium adoptée par les états, banques et marques globales.",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "Vieille ville de Zurich, Suisse",
      endpointLease: "SECURE ENDPOINT LEASE",
      products: "Produits",
      solutions: "Solutions",
      company: "Société",
      contactHeader: "Contact",
    }
  },
  es: {
    nav: {
      threats: "Amenazas",
      howItWorks: "Funciona",
      modules: "Módulos",
      playground: "Laboratorio",
      ecosystem: "Ecosistema",
      ledger: "Libro de Registro",
      tunnel: "Túnel Seguro",
      launch: "Iniciar Escaneo",
      shLine: "por Shaduli"
    },
    hero: {
      securing: "AIVERSE PROTEGIENDO LA AUTENTICIDAD DIGITAL GLOBAL",
      titlePre: "Construyendo Confianza ",
      titleSpan: "en la Era de la IA.",
      subtitle: "AiVerse detecta contenido sintético dañino, identifica ciberamenazas y certifica la autenticidad digital para gobiernos y corporaciones globales.",
      ctasScan: "Iniciar Escaneo de Confianza",
      ctasDemo: "Ver Demostración",
      monitoring: "⚠️ MONITOREO ACTIVO: ASEGURANDO 4.8M CANALES EN ESTE INSTANTE",
      threatIntel: "Inteligencia de Amenazas",
      monitoringActive: "Monitoreo global activo",
      deepfakeDet: "Deepfake Detectado",
      deepfakeDetMsg: "Identificado como generación sintética mediante IA.",
      justNow: "Ahora mismo • Norteamérica",
      voiceAnomaly: "Anomalía de Voz",
      voiceAnomalyMsg: "Verificación fallida: Firma biométrica sintética artificial.",
      twoMAgo: "Hace 2m • Unión Europea",
      originVerified: "Origen Verificado",
      originVerifiedMsg: "Trazabilidad completa: Archivo digital auténtico.",
      fiveMAgo: "Hace 5m • Asia-Pacífico",
      trustScore: "Índice de Confianza",
      scannedContent: "Contenido Escaneado",
      scannedSub: "Objetos validados en tiempo real",
      threatsIsolated: "Amenazas IA Aisladas",
      threatsSub: "Deepfakes bloqueados en la entrada",
      accuracyVector: "Vector de Precisión",
      accuracySub: "Confianza forense optimizada",
      enterpriseCovered: "Empresas Aseguradas",
      enterpriseSub: "Registros gubernamentales y bancarios",
    },
    scanModal: {
      decentralized: "MOTOR DE ANÁLISIS DESCENTRALIZADO",
      title: "Espacio Diagnóstico de Confianza Seguro",
      subtitle: "Ingesta segura en un entorno aislado (sandbox). Pegue enlaces de redes sociales, textos o hashes para verificar su integridad.",
      imgBtn: "📸 Imagen (.jpg)",
      voiceBtn: "🎙️ Nota de Voz",
      videoBtn: "🎥 Video Deepfake",
      emailBtn: "📩 Email Falso",
      inputParams: "Parámetros del archivo a procesar",
      secureActive: "TÚNEL SEGURO ACTIVO",
      dragDrop: "Arrastre el archivo o explore sus directorios",
      dragSub: "Soporte PDF, WAV, PNG, MP4. Registros privados SOC2.",
      ingestBtn: "INGRESAR Y ANALIZAR ARCHIVO",
      stage1: "ETAPA 1/2: COMPROBACIÓN DE BORDES DE PÍXEL",
      stage2: "ETAPA 2/2: CÁLCULO DE COHERENCIA DE FIRMA",
      criticalTitle: "DIAGNÓSTICO CRÍTICO",
      authScore: "Puntaje de Autenticidad",
      lowScore: "(BAJO)",
      classification: "Clasificación",
      legalAdmissible: "Admisible Legalmente",
      certificate: "Certificado de Trazabilidad Verificado",
      outputTitle: "Resultado Forense:",
      outputMsg: "Desviación de malla GAN. La compresión fonética no coincide con el perfil humano real. Acciones registradas.",
      ingestNext: "Siguiente Muestra",
      closeWorkspace: "Cerrar Espacio"
    },
    threats: {
      category: "Sección 02 // Riesgos Generativos",
      title: "El Paisaje de Amenazas IA",
      subtitle: "Los contenidos sintéticos alcanzan la fidelidad humana. Revise los vectores de ataque principales.",
      reconnaissance: "RECONOCIMIENTO DE AMENAZAS",
      activeInspect: "Inspección Activa",
      inactiveInspect: "Inspeccionar Vektor",
      deepNoiseMatch: "CONCORDANCIA DE RUIDO PROFUNDO:",
      latentArtifacts: "ARTEFACTOS LATENTES SOSPECHOSOS",
      dragSlider: "ARRASTRE EN LA VISTA PREVIA PARA MAPEAR",
      ganArtifacts: "Errores de costura GAN",
      pixelInconsistencies: "Inconsistencias aisladas en la malla en contornos de piel",
      cleanOriginal: "METADATOS ORIGINALES LIMPIOS",
      verifiedRaw: "Registro del sensor de la cámara original intacto",
    },
    workflow: {
      category: "Sección 03 // Pipeline Forense",
      title: "Cómo funciona AiVerse",
      subtitle: "Nuestro escáner paralelo mutimodelo descodifica el ADN digital capa por capa. Experimente la secuencia.",
      auditEngine: "MOTOR DE AUDITORÍA v4.21",
      sandboxTitle: "Buzón de Escaneo Forense Interactivo",
      sandboxSub: "Seleccione una muestra para iniciar el escaneo lógico. Vea los algoritmos actuar.",
      scanRunning: "Forense en ejecución",
      resetEcosystem: "Restablecer Entorno",
      secureIngest: "Ingresar muestra y ejecutar",
      consoleTitle: "TELEMÉTRICA CONSOLA SHIELD",
      consoleSub: "TIMESTAMP: 2026-06-06 UTC",
      terminalIdleSubtitle: "Seleccione un archivo y presione \"Ingresar muestra y ejecutar\" para iniciar.",
      processingStage: "[PROCESANDO COHERENCIA DE METADATOS Y MALLAS]"
    },
    modules: {
      category: "Sección 04 // Catálogo de Soluciones",
      title: "Módulos de la Plataforma",
      subtitle: "Soluciones de gobernanza soberana diseñadas para proteger la identidad corporativa, autenticidad y medios.",
      kpiLabel: "Objetivo KPI",
    },
    demo: {
      category: "Secciones 05–13 // Laboratorio Lógico",
      title: "Centro de Diagnóstico Interactivo",
      subtitle: "Simule análisis de voz, mapas de origen de datos, costuras de imágenes y deepfakes en SaaS.",
      orgsCovered: "EMPRESAS PROTEGIDAS",
      orgsVal: "4,800 organizaciones",
    },
    ecosystem: {
      nodeSelected: "Nodo seleccionado actualmente: ",
      brainTitle: "AiVerse ONE",
      brainSub: "Cerebro Unificador",
    },
    metrics: {
      category: "CASOS FORENSES REGISTRADOS",
      caseStudies: "Evaluación Continua de Rendimiento",
      caseSubtitle: "Evaluamos nuestros modelos paralelos diariamente frente a estándares internacionales.",
      avgAccuracy: "98.7% Prom.",
      avgAccuracyTag: "Precisión de Píxel",
      latentDelay: "Frecuencia de Retraso",
      restartBtn: "Reiniciar Simulación",
    },
    footer: {
      brandDesc: "Haciendo la IA responsable, rastreable y transparente. La plataforma elegida por bancos centrales, gobiernos y marcas.",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "Casco Antiguo de Zúrich, Suiza",
      endpointLease: "SECURE ENDPOINT LEASE",
      products: "Productos",
      solutions: "Soluciones",
      company: "Compañía",
      contactHeader: "Contacto",
    }
  },
  ja: {
    nav: {
      threats: "脅威の展望",
      howItWorks: "機能メカニズム",
      modules: "プラットフォームモジュール",
      playground: "検証ラボ",
      ecosystem: "エコロジカル接続",
      ledger: "精度監査台帳",
      tunnel: "セキュアトンネル",
      launch: "信頼性スキャン開始",
      shLine: "Shaduli 開発"
    },
    hero: {
      securing: "AIVERSE 全球デジタルコンテンツ真正性担保プログラム動作中",
      titlePre: "AI時代の ",
      titleSpan: "真正性信頼基盤を構築。",
      subtitle: "AiVerseは、政府機関やグローバル企業を標的とした有害なAI生成コンテンツの検知、サイバー脅威の特定、およびデジタルの真正性認証を実行します。",
      ctasScan: "信頼性スキャン開始",
      ctasDemo: "製品デモを視聴",
      monitoring: "⚠️ リアルタイム監視：世界480万以上の敵対的チャンネルを自動防御中",
      threatIntel: "脅威インテリジェンスフィード",
      monitoringActive: "グローバルモニタリング稼働中",
      deepfakeDet: "ディープフェイクを検出",
      deepfakeDetMsg: "メディアソースが合成AIによる生成物であると判定されました。",
      justNow: "今すぐ • 北米ノード",
      voiceAnomaly: "音声生体情報の異常",
      voiceAnomalyMsg: "判定：合成音声署名に起因するバイオメトリクス不一致。",
      twoMAgo: "2分前 • 欧州連合ノード",
      originVerified: "電子透かし起源の確認完了",
      originVerifiedMsg: "オリジナル証明：安全な真正デジタル資産として登録完了。",
      fiveMAgo: "5分前 • アジア太平洋ノード",
      trustScore: "信頼スコアインデックス",
      scannedContent: "累計検証コンテンツ",
      scannedSub: "リアルタイムで認証されたオブジェクト数",
      threatsIsolated: "隔離されたAI脅威",
      threatsSub: "ゲートウェイでブロックされたフェイクメディア数",
      accuracyVector: "判定精度ベクトル",
      accuracySub: "チューニング済みフォレンジックの信頼度",
      enterpriseCovered: "保護企業の組織数",
      enterpriseSub: "政府機関・銀行システム等登記機関",
    },
    scanModal: {
      decentralized: "AIVERSE 分散型真正性検証エンジン",
      title: "セキュア監査ワークスペース",
      subtitle: "防弾サンドボックスによるペイロード解析。ソーシャルメディアURL、メール原文、ファイルのハッシュを解析し真偽性レポートを生成します。",
      imgBtn: "📸 画像解析 (.jpg)",
      voiceBtn: "🎙️ 音声波形解析",
      videoBtn: "🎥 ビデオ検証",
      emailBtn: "📩 フィッシング詐欺検出",
      inputParams: "インプット・パラメータ",
      secureActive: "セキュア接続トンネルアクティブ",
      dragDrop: "ファイルをドラッグ＆ドロップ、またはディレクトリを参照",
      dragSub: "PDF, WAV, PNG, MP4 対応。SOC2準拠暗号化プライベート防御ログ。",
      ingestBtn: "データ取り込み・解析を実行",
      stage1: "ステージ 1/2: ピクセル・グリッド整合性チェック",
      stage2: "ステージ 2/2: 音響・署名バイパスコヒーレンス算出",
      criticalTitle: "診断：クリティカル警告",
      authScore: "真正性評価スコア",
      lowScore: "（著しい低下レベル）",
      classification: "モデル解析分類",
      legalAdmissible: "法的証拠能力の担保",
      certificate: "真正性証明証書付与完了",
      outputTitle: "監査結果：",
      outputMsg: "GANグリッドの不一致。機械合成特有の不自然なスペクトラム異常とバイオメトリクスの不整合を検出。境界台帳に防御アクションが書き込まれました。",
      ingestNext: "次のサンプルを検証",
      closeWorkspace: "ワークスペースを閉じる"
    },
    threats: {
      category: "セクション 02 // 生成AIがもたらす地政学的リスク",
      title: "AI 生成脅威の展望",
      subtitle: "合成コンテンツは急速に人間レベルの忠実度に達しています。主要な攻撃ベクトルと侵食の状況について確認してください。",
      reconnaissance: "AIVERSE 脅威偵察防衛",
      activeInspect: "監査中",
      inactiveInspect: "ベクトル監査",
      deepNoiseMatch: "画像の潜在ノイズ解析結果:",
      latentArtifacts: "潜在するGAN合成歪み箇所",
      dragSlider: "スライダーを動かして検出箇所を確認",
      ganArtifacts: "GANの接続境界の矛盾",
      pixelInconsistencies: "肌の境界線におけるピクセルグリッドの不規則性を分離して特定",
      cleanOriginal: "改ざんのないオリジナルメタデータ",
      verifiedRaw: "安全なカメラオリジナル記録が保持されています",
    },
    workflow: {
      category: "セクション 03 // リアルタイムフォレンジックパイプライン",
      title: "AiVerse の動作フロー",
      subtitle: "マルチ並列型スキャンモデルが、デジタルの真正性チェックを実行します。",
      auditEngine: "AIVERSE 監査コアシステム v4.21",
      sandboxTitle: "フォレンジックスキャン・サンドボックス",
      sandboxSub: "検証したいデジタル資産を選択して自動ロードを開始し、バックグラウンドの解析フローを追跡します。",
      scanRunning: "真正性スキャン実行中",
      resetEcosystem: "状態をクリア",
      secureIngest: "データ取り込み＆監査開始",
      consoleTitle: "スキャンテレメトリ監査ログ",
      consoleSub: "記録時刻: 2026-06-06 UTC",
      terminalIdleSubtitle: "対象オブジェクトを選択し「データ取り込み＆監査開始」をクリックして検証します。",
      processingStage: "[真正性チェック実行中：ニューラルハッシュ比較完了]"
    },
    modules: {
      category: "セクション 04 // ユースケース別のモジュール",
      title: "提供モジュール",
      subtitle: "企業コミニュケーション、アイデンティティ防御、メディア証明のための完全なる信頼性プロトコル。",
      kpiLabel: "KPI達成度",
    },
    demo: {
      category: "セクション 05–13 // 診断デモラボ",
      title: "インタラクティブ検証プラザ",
      subtitle: "ディープフェイク検出、音声スペクトログラム、トレーサビリティマップ、および詐欺防止フィルターをテストします。",
      orgsCovered: "保護運用企業・機関",
      orgsVal: "4,800組織以上",
    },
    ecosystem: {
      nodeSelected: "選択されているアクティブノード: ",
      brainTitle: "AiVerse ONE",
      brainSub: "防衛統合コア",
    },
    metrics: {
      category: "検証済み成功実績ログ",
      caseStudies: "コンプライアンス適合評価実績",
      caseSubtitle: "国際フォレンジック標準機関が定義する厳しい検出信頼性ベンチマークテストを毎時間実行しています。",
      avgAccuracy: "平均精度 98.7%",
      avgAccuracyTag: "ピクセルレベル認証",
      latentDelay: "処理バッファ遅延",
      restartBtn: "シミュレーションを初期化",
    },
    footer: {
      brandDesc: "AIをより安全、追跡可能、そして透明度の高い存在へ。世界の中央銀行、国家登記機関、および信頼されるガバナンス機関で運用されています。",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "スイス・チューリッヒ特別区",
      endpointLease: "セキュア接続ノードリース中",
      products: "製品情報",
      solutions: "ソリューション",
      company: "運営組織",
      contactHeader: "連絡先デスク",
    }
  },
  ml: {
    nav: {
      threats: "ഭീഷണി വിശകലനം",
      howItWorks: "പ്രവർത്തന രീതി",
      modules: "പ്ലാറ്റ്ഫോം ഘടകങ്ങൾ",
      playground: "പ്ലേഗ്രൗണ്ട് സെൻ്റർ",
      ecosystem: "ഇക്കോസിസ്റ്റം ടോപ്പോളജി",
      ledger: "തുല്യതാ ലെഡ്ജർ",
      tunnel: "സുരക്ഷിത ടണൽ",
      launch: "ട്രസ്റ്റ് സ്കാൻ ആരംഭിക്കുക",
      shLine: "ഷാദുലി എഴുതിയത്"
    },
    hero: {
      securing: "AIVERSE ആഗോള ഡിജിറ്റൽ വിശ്വാസ്യത ഉറപ്പാക്കുന്നു",
      titlePre: "വിശ്വാസം വളർത്തുന്നു ",
      titleSpan: "AI യുഗത്തിൽ.",
      subtitle: "AiVerse ദോഷകരമായ AIസൃഷ്ടിത ഉള്ളടക്കങ്ങൾ കണ്ടെത്തുകയും സൈബർ ഭീഷണികൾ തടയുകയും ഡിജിറ്റൽ വിശ്വാസ്യത തെളിയിക്കുകയും ചെയ്യുന്നു.",
      ctasScan: "സ്കാൻ ആരംഭിക്കുക",
      ctasDemo: "ഡെമോ കാണുക",
      monitoring: "⚠️ സജീവം: 4.8M അഡ്വേർസറിയൽ ചാനലുകൾ നിരീക്ഷിക്കുന്നു",
      threatIntel: "ഭീഷണി വിവരങ്ങൾ",
      monitoringActive: "ആഗോള നിരീക്ഷണം സജീവം",
      deepfakeDet: "ഡീപ്ഫേക്ക് കണ്ടെത്തി",
      deepfakeDetMsg: "മീഡിയ ഉറവിടം വ്യാജ AI നിർമ്മിതമാണെന്ന് കണ്ടെത്തി.",
      justNow: "ഇപ്പോൾ തന്നെ • വടക്കേ അമേരിക്ക",
      voiceAnomaly: "ശബ്ദ വ്യതിയാനം",
      voiceAnomalyMsg: "പരിശോധന പരാജയപ്പെട്ടു: കൃത്രിമ ബയോമെട്രിക് ഒപ്പ്.",
      twoMAgo: "2 മിനിറ്റ് മുൻപ് • യൂറോപ്യൻ യൂണിയൻ",
      originVerified: "ഉറവിടം സാക്ഷ്യപ്പെടുത്തി",
      originVerifiedMsg: "ഉറവിട പരിശോധന പൂർത്തിയായി: യഥാർത്ഥ ഉള്ളടക്കം.",
      fiveMAgo: "5 മിനിറ്റ് മുൻപ് • ഏഷ്യ-പസഫിക്",
      trustScore: "വിശ്വാസ്യത സ്കോർ സൂചിക",
      scannedContent: "ആകെ സ്കാൻ ചെയ്തത്",
      scannedSub: "തത്സമയ പരിശോധന നടത്തിയ വസ്തുക്കൾ",
      threatsIsolated: "ഒറ്റപ്പെടുത്തിയ ഭീഷണികൾ",
      threatsSub: "തടയപ്പെട്ട വ്യാജങ്ങൾ",
      accuracyVector: "കൃത്യതാ വെക്റ്റർ",
      accuracySub: "കൃത്യമായ ഫോറൻസിക് വിശ്വാസ്യത",
      enterpriseCovered: "സുരക്ഷിതമാക്കിയ സ്ഥാപനങ്ങൾ",
      enterpriseSub: "ഗവൺമെന്റുകളും ബാങ്ക് രജിസ്ട്രികളും",
    },
    scanModal: {
      decentralized: "AIVERSE വികേന്ദ്രീകൃത സ്കാനിംഗ് എഞ്ചിൻ",
      title: "സുരക്ഷിത വിശ്വാസ്യത കണ്ടെത്തൽ വർക്ക്സ്പേസ്",
      subtitle: "സുരക്ഷിതമായ സാൻഡ്ബോക്സ് വഴി ഫയലുകൾ, ലിങ്കുകൾ, ഇമെയിലുകൾ അല്ലെങ്കിൽ ഹാഷുകൾ പരിശോധിക്കുക.",
      imgBtn: "📸 ചിത്രം (.jpg)",
      voiceBtn: "🎙️ ശബ്ദ വിശകലനം",
      videoBtn: "🎥 വീഡിയോ ഡീപ്ഫേക്ക്",
      emailBtn: "📩 ഫിഷിംഗ് ഇമെയിൽ",
      inputParams: "ഇൻപുട്ട് ഘടകങ്ങൾ",
      secureActive: "സുരക്ഷിത ടണൽ സജീവം",
      dragDrop: "ഫയൽ ഡ്രാഗ് ചെയ്യുക അല്ലെങ്കിൽ ബ്രൗസ് ചെയ്യുക",
      dragSub: "PDF, WAV, PNG, MP4 പിന്തുണയ്ക്കുന്നു. SOC2 പ്രകാരം എൻക്രിപ്റ്റ് ചെയ്ത ലോഗുകൾ.",
      ingestBtn: "വിശകലനം ആരംഭിക്കുക",
      stage1: "ഘട്ടം 1/2: പിക്സൽ സീം പരിശോധന",
      stage2: "ഘട്ടം 2/2: ഒപ്പ് യോജിപ്പ് കണക്കുകൂട്ടൽ",
      criticalTitle: "ഗുരുതരമായ കണ്ടെത്തൽ",
      authScore: "യഥാർത്ഥ്യ സ്കോർ",
      lowScore: "(കുറവ്)",
      classification: "വർഗ്ഗീകരണം",
      legalAdmissible: "നിയമപരമായ സ്വീകാര്യത",
      certificate: "പരിശോധിച്ചു സാക്ഷ്യപ്പെടുത്തിയ സർട്ടിഫിക്കറ്റ്",
      outputTitle: "AI ഫോറൻസിക് ഔട്ട്പുട്ട്:",
      outputMsg: "GAN ഗ്രിഡ് വൈരുധ്യം. ശബ്ദ തരംഗങ്ങൾ യഥാർത്ഥ മനുഷ്യന്റേതുമായി പൊരുത്തപ്പെടുന്നില്ല. സുരക്ഷാ ലോഗുകളിൽ രേഖപ്പെടുത്തി.",
      ingestNext: "അടുത്തത് പരിശോധിക്കുക",
      closeWorkspace: "വർക്ക്സ്പേസ് അടയ്ക്കുക"
    },
    threats: {
      category: "വിഭാഗം 02 // ജനറേറ്റീവ് അപകടസാധ്യതകൾ",
      title: "AI ഭീഷണി മേഖല",
      subtitle: "കൃത്രിമ സൃഷ്ടികൾ മനുഷ്യനേക്കാൾ മികച്ചതാകുന്നു. സൈബർ കുറ്റവാളികൾ ഉപയോഗിക്കുന്ന പ്രധാന മാർഗ്ഗങ്ങൾ പരിശോധിക്കുക.",
      reconnaissance: "AIVERSE ഭീഷണി പരിശോധന",
      activeInspect: "സജീവ പരിശോധന",
      inactiveInspect: "പരിശോധനാ വെക്ടർ",
      deepNoiseMatch: "ചിത്രത്തിലെ നോയിസ് പരിശോധന:",
      latentArtifacts: "സംശയിക്കപ്പെടുന്ന വൈകല്യങ്ങൾ",
      dragSlider: "പരിശോധിക്കുന്നതിനായി സ്ലൈഡർ നീക്കുക",
      ganArtifacts: "GAN സീം പരാജയങ്ങൾ കണ്ടെത്തി",
      pixelInconsistencies: "ചർമ്മ ഭാഗങ്ങളിൽ പിക്സൽ അപാകതകൾ കണ്ടെത്തി",
      cleanOriginal: "യഥാർത്ഥ മെറ്റാഡാറ്റ",
      verifiedRaw: "ക്യാമറ വിവരങ്ങൾ മാറ്റമില്ലാതെ ലഭ്യമാണ്",
    },
    workflow: {
      category: "വിഭാഗം 03 // ഫോറൻസിക് പൈപ്പ്ലൈൻ",
      title: "AiVerse പ്രവർത്തിക്കുന്നത് എങ്ങനെ",
      subtitle: "ഞങ്ങളുടെ മൾട്ടി-മോഡൽ സമാന്തര സ്കാനർ ഡിജിറ്റൽ ഡിഎൻഎ വിശകലനം ചെയ്യുന്നു. ലൈവ് പ്രക്രിയ നിരീക്ഷിക്കുക.",
      auditEngine: "AIVERSE ഓഡിറ്റ് എഞ്ചിൻ v4.21",
      sandboxTitle: "ഇന്ററാക്ടീവ് ഫോറൻസിക് സ്കാനിംഗ് സാൻഡ്ബോക്സ്",
      sandboxSub: "ചുവടെ ഒരു മാതൃക തിരഞ്ഞെടുത്ത് സ്കാൻ ആരംഭിക്കുക. അൽഗോരിതങ്ങൾ പ്രവർത്തിക്കുന്നത് കാണുക.",
      scanRunning: "പരിശോധന പുരോഗമിക്കുന്നു",
      resetEcosystem: "റീസെറ്റ് ചെയ്യുക",
      secureIngest: "റൺ ചെയ്യുക",
      consoleTitle: "സ്കാൻ ടെലിമെട്രി ഷീൽഡ് കൺസോൾ",
      consoleSub: "സമയം: 2026-06-06 UTC",
      terminalIdleSubtitle: "ഒരു മാതൃക തിരഞ്ഞെടുത്ത് റൺ ചെയ്യുക.",
      processingStage: "[പ്രക്രിയ പുരോഗമിക്കുന്നു ... ന്യൂറൽ ഹാഷിങ് പാറ്റേണുകൾ ആരംഭിച്ചു]"
    },
    modules: {
      category: "വിഭാഗം 04 // ഉൽപ്പന്ന പ്രദർശനം",
      title: "പ്ലാറ്റ്ഫോം ഘടകങ്ങൾ",
      subtitle: "സ്ഥാപനങ്ങൾക്കും ആശയവിനിമയങ്ങൾക്കുമായുള്ള സുരക്ഷിത പ്ലാറ്റ്ഫോം ഘടകങ്ങൾ.",
      kpiLabel: "KPI ലക്ഷ്യം",
    },
    demo: {
      category: "വിഭാഗം 05–13 // രോഗനിർണ്ണയ ലബോറട്ടറി",
      title: "ഇന്ററാക്ടീവ് രോഗനിർണ്ണയ കേന്ദ്രം",
      subtitle: "ഡീപ്ഫേക്ക് കണ്ടെത്തൽ, ശബ്ദ സ്പെക്ട്രോഗ്രാമുകൾ എന്നിവ പരീക്ഷിച്ചു നോക്കുക.",
      orgsCovered: "സംരക്ഷിക്കപ്പെട്ട ഓർഗനൈസേഷനുകൾ",
      orgsVal: "4,800 സ്ഥാപനങ്ങൾ",
    },
    ecosystem: {
      nodeSelected: "തിരഞ്ഞെടുത്ത നോഡ്: ",
      brainTitle: "AiVerse ONE",
      brainSub: "സംയോജിത ബുദ്ധി",
    },
    metrics: {
      category: "വിജയകരമായ ഓഡിറ്റ് റെക്കോർഡുകൾ",
      caseStudies: "തുടർച്ചയായ പ്രകടന വിലയിруത്തൽ",
      caseSubtitle: "ഞങ്ങളുടെ നവീന ഫോറൻസിക് മോഡലുകൾ തുടർച്ചയായി പരിശോധിച്ച് മെച്ചപ്പെടുത്തുന്നു.",
      avgAccuracy: "98.7% ശരാശരി",
      avgAccuracyTag: "പിക്സൽ കൃത്യത",
      latentDelay: "താമസം",
      restartBtn: "വീണ്ടും ആരംഭിക്കുക",
    },
    footer: {
      brandDesc: "AI ഉത്തരവാദിത്തമുള്ളതും സുതാര്യവുമാക്കുന്നു. മുൻനിര ബാങ്കുകളും ഗവൺമെന്റുകളും വിശ്വസിക്കുന്ന പ്രീമിയം ഗവേണൻസ് പ്ലാറ്റ്ഫോം.",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "സൂറിച്ച്, സ്വിറ്റ്സർലൻഡ്",
      endpointLease: "സുരക്ഷിത എൻഡ് പോയിന്റ് ലീസ്",
      products: "ഉൽപ്പന്നങ്ങൾ",
      solutions: "പരിഹാരങ്ങൾ",
      company: "കമ്പനി",
      contactHeader: "ബന്ധപ്പെടുക",
    }
  },
  hi: {
    nav: {
      threats: "खतरा परिदृश्य",
      howItWorks: "यह कैसे काम करता है",
      modules: "प्लेटफ़ॉर्म मॉड्यूल",
      playground: "प्लेग्राउंड सेंटर",
      ecosystem: "इकोसिस्टम टोपोलॉजी",
      ledger: "सटीकता बहीखाता",
      tunnel: "सुरक्षित टनल",
      launch: "ट्रस्ट स्कैन शुरू करें",
      shLine: "शादुली द्वारा"
    },
    hero: {
      securing: "AIVERSE वैश्विक डिजिटल प्रामाणिकता सुरक्षित कर रहा है",
      titlePre: "विश्वास का निर्माण ",
      titleSpan: "AI युग में।",
      subtitle: "AiVerse हानिकारक AI-जनित सामग्री का पता लगाता है, साइबर खतरों की पहचान करता है, और वैश्विक उद्यमों के लिए डिजिटल प्रामाणिकता को सत्यापित करता है।",
      ctasScan: "ट्रस्ट स्कैन शुरू करें",
      ctasDemo: "डेमो देखें",
      monitoring: "⚠️ निगरानी सक्रिय: आज 4.8M प्रतिकूल चैनलों को सुरक्षित किया जा रहा है",
      threatIntel: "खतरा इंटेलिजेंस",
      monitoringActive: "वैश्विक निगरानी सक्रिय",
      deepfakeDet: "डीपफेक का पता चला",
      deepfakeDetMsg: "मीडिया स्रोत की पहचान सिंथेटिक AI जनरेशन के रूप में हुई।",
      justNow: "अभी-अभी • उत्तरी अमेरिका",
      voiceAnomaly: "आवाज विसंगति",
      voiceAnomalyMsg: "सत्यापन विफल: सिंथेटिक बायोमेट्रिक सिग्नेचर।",
      twoMAgo: "2 मिनट पहले • यूरोपीय संघ",
      originVerified: "मूल सत्यापित",
      originVerifiedMsg: "स्रोत की खोज पूरी: प्रामाणिक डिजिटल संपत्ति।",
      fiveMAgo: "5 मिनट पहले • एशिया-प्रशांत",
      trustScore: "ट्रस्ट स्कोर इंडेक्स",
      scannedContent: "कुल स्कैन की गई सामग्री",
      scannedSub: "वास्तविक समय सत्यापित वस्तुएं",
      threatsIsolated: "AI खतरों को अलग किया गया",
      threatsSub: "द्वार पर डीपफेक रोके गए",
      accuracyVector: "सटीकता वेक्टर",
      accuracySub: "ट्यून्ड फोरेंसिक आत्मविश्वास",
      enterpriseCovered: "उद्यम संगठन सुरक्षित",
      enterpriseSub: "सरकारें और बैंक रजिस्ट्रियां",
    },
    scanModal: {
      decentralized: "AIVERSE विकेंद्रीकृत स्कैन इंजन",
      title: "सुरक्षित विश्वास नैदानिक कार्यक्षेत्र",
      subtitle: "सुरक्षित सैंडबॉक्स पेलोड अंतर्ग्रहण। डिजिटल प्रामाणिकता रिपोर्ट की समीक्षा करने के लिए सोशल URL, ईमेल, या फ़ाइल हैश पेस्ट करें।",
      imgBtn: "📸 छवि (.jpg)",
      voiceBtn: "🎙️ आवाज व्याख्या",
      videoBtn: "🎥 वीडियो डीपफेक",
      emailBtn: "📩 फ़िशिंग ईमेल",
      inputParams: "इनपुट पेलोड पैरामीटर्स",
      secureActive: "सुरक्षित सुरंग सक्रिय",
      dragDrop: "फ़ाइल को यहाँ खींचें या निर्देशिका ब्राउज़ करें",
      dragSub: "PDF, WAV, PNG, MP4 समर्थन। एन्क्रिप्टेड, SOC2-सैंडबॉक्स निजी लॉग।",
      ingestBtn: "सुरक्षित रूप से ग्रहण और विश्लेषण करें",
      stage1: "चरण 1/2: पिक्सेल सीम सत्यापन",
      stage2: "चरण 2/2: हस्ताक्षर सुसंगतता गणना",
      criticalTitle: "नैदानिक गंभीर",
      authScore: "प्रामाणिकता स्कोर",
      lowScore: "(कम)",
      classification: "वर्गीकरण",
      legalAdmissible: "कानूनी रूप से स्वीकार्य",
      certificate: "ट्रेस सत्यापित प्रमाण पत्र",
      outputTitle: "AI फोरेंसिक परिणाम:",
      outputMsg: "GAN ग्रिड विसंगति पाई गई। भाषण ध्वन्यात्मक संपीड़न भौतिक मानव आवाज प्रोफाइल से मेल नहीं खाता है। सुरक्षा क्रियाएं बहीखाता में दर्ज।",
      ingestNext: "अगला नमूना लें",
      closeWorkspace: "कार्यक्षेत्र बंद करें"
    },
    threats: {
      category: "अनुभाग 02 // जनरेटिव जोखिम",
      title: "AI खतरा परिदृश्य",
      subtitle: "सिंथेटिक सामग्री मानव-स्तर की सटीकता तक पहुंच रही है। साइबर अपराधियों द्वारा उपयोग किए जाने वाले मुख्य हमलों की समीक्षा करें।",
      reconnaissance: "AIVERSE खतरा टोह",
      activeInspect: "सक्रिय निरीक्षण",
      inactiveInspect: "निरीक्षण वेक्टर",
      deepNoiseMatch: "छवि गहरे शोर मिलान:",
      latentArtifacts: "संदिग्ध छिपी हुई विसंगतियाँ",
      dragSlider: "निरीक्षण करने के लिए पूर्वावलोकन में स्लाइडर खींचें",
      ganArtifacts: "GAN सीम विफलताएं मिलीं",
      pixelInconsistencies: "त्वचा के किनारों पर पिक्सेल ग्रिड विसंगतियां",
      cleanOriginal: "साफ़ मूल मेटाडेटा",
      verifiedRaw: "सत्यापित रॉ कैमरा सेंसर रिकॉर्ड बरकरार",
    },
    workflow: {
      category: "अनुभाग 03 // फोरेंसिक पाइपलाइन",
      title: "AiVerse कैसे काम करता है",
      subtitle: "हमारा मल्टी-मॉडल समानांतर स्कैनर डिजिटल डीएनए को परत-दर-परत डिकोड करता है। वास्तविक समय की प्रक्रिया का अनुभव करें।",
      auditEngine: "AIVERSE ऑडिट इंजन v4.21",
      sandboxTitle: "इंटरैक्टिव फोरेंसिक स्कैनिंग सैंडबॉक्स",
      sandboxSub: "स्कैन शुरू करने के लिए नीचे एक नमूना चुनें। प्रत्येक एल्गोरिदम को काम करते हुए देखें।",
      scanRunning: "फोरेंसिक सक्रिय है",
      resetEcosystem: "रीसेट करें",
      secureIngest: "सुरक्षित ग्रहण और चलाएं",
      consoleTitle: "स्कैन टेलीमेट्री शील्ड कंसोल",
      consoleSub: "समय: 2026-06-06 UTC",
      terminalIdleSubtitle: "एक पेलोड चुनें और स्कैन शुरू करने के लिए \"सुरक्षित ग्रहण और चलाएं\" पर क्लिक करें।",
      processingStage: "[प्रसंस्करण चरण ... तंत्रिका हैशिंग पैटर्न शुरू]"
    },
    modules: {
      category: "अनुभाग 04 // उत्पाद शोकेस",
      title: "प्लेटफ़ॉर्म मॉड्यूल",
      subtitle: "कॉर्पोरेट संचार, पहचान सुरक्षा, और मीडिया सुरक्षा के लिए इंजीनियर किए गए संप्रभु विश्वास वर्टिकल।",
      kpiLabel: "KPI लक्ष्य",
    },
    demo: {
      category: "अनुभाग 05-13 // नैदानिक प्रयोगशाला",
      title: "इंटरैक्टिव नैदानिक केंद्र",
      subtitle: "सक्रिय SaaS वातावरण में डीपफेक पहचान, ऑडियो स्पेक्ट्रोग्राम और साइबर फ़िल्टर का अनुकरण करें।",
      orgsCovered: "सुरक्षित संगठन",
      orgsVal: "4,800 संगठन",
    },
    ecosystem: {
      nodeSelected: "वर्तमान में चयनित नोड: ",
      brainTitle: "AiVerse ONE",
      brainSub: "एकीकृत मस्तिष्क",
    },
    metrics: {
      category: "सफल ऑडिट रिकॉर्ड",
      caseStudies: "सतत प्रदर्शन मूल्यांकन",
      caseSubtitle: "हम दैनिक रूप से अंतर्राष्ट्रीय फोरेंसिक मानकों के खिलाफ हमारे मॉडलों को बेंचमार्क करते हैं।",
      avgAccuracy: "98.7% औसत",
      avgAccuracyTag: "पिक्सेल सटीकता",
      latentDelay: "अव्यक्त देरी",
      restartBtn: "सिमुलेशन पुनरारंभ करें",
    },
    footer: {
      brandDesc: "AI को जवाबदेह, खोजने योग्य और भरोसेमंद बनाना। वैश्विक संगठनों, बैंकों और सार्वजनिक क्षेत्रों द्वारा विश्वसनीय प्रीमियम शासन मंच।",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "ज्यूरिख पुराना शहर, स्विट्जरलैंड",
      endpointLease: "सुरक्षित एंडपॉइंट लीज",
      products: "उत्पाद",
      solutions: "समाधान",
      company: "कंपनी",
      contactHeader: "संपर्क डेस्क",
    }
  },
  ar: {
    nav: {
      threats: "نموذج التهديدات",
      howItWorks: "كيف يعمل",
      modules: "وحدات المنصة",
      playground: "مركز التجربة",
      ecosystem: "بنية النظام",
      ledger: "سجل الدقة",
      tunnel: "النفق الآمن",
      launch: "إطلاق فحص الثقة",
      shLine: "بواسطة شادولي"
    },
    hero: {
      securing: "AIVERSE تأمين الموثوقية الرقمية العالمية",
      titlePre: "بناء الثقة ",
      titleSpan: "في عصر الذكاء الاصطناعي.",
      subtitle: "يكشف AiVerse عن المحتوى الضار الذي تم إنشاؤه بواسطة الذكاء الاصطناعي، ويحدد التهديدات السيبرانية، ويتحقق من الموثوقية الرقمية للحكومات والمؤسسات العالمية.",
      ctasScan: "إطلاق فحص الثقة",
      ctasDemo: "مشاهدة العرض التجريبي",
      monitoring: "⚠️ المراقبة نشطة: تأمين 4.8 مليون قناة معادية اليوم",
      threatIntel: "استخبارات التهديدات",
      monitoringActive: "المراقبة العالمية نشطة",
      deepfakeDet: "تم اكتشاف ديب فيك",
      deepfakeDetMsg: "تم تحديد مصدر الوسائط كتوليد اصطناعي للذكاء الاصطناعي.",
      justNow: "الآن • أمريكا الشمالية",
      voiceAnomaly: "شذوذ صوتي",
      voiceAnomalyMsg: "فشل التحقق: توقيع غامض اصطناعي للقياس الحيوي.",
      twoMAgo: "منذ دقيقتين • الاتحاد الأوروبي",
      originVerified: "تم التحقق من الأصل",
      originVerifiedMsg: "اكتمل تتبع المصدر: أصل رقمي موثوق.",
      fiveMAgo: "منذ 5 دقائق • آسيا والمحيط الهادئ",
      trustScore: "مؤشر درجة الثقة",
      scannedContent: "إجمالي المحتوى المفحوص",
      scannedSub: "العناصر التي تم التحقق منها في الوقت الفعلي",
      threatsIsolated: "تم عزل تهديدات الذكاء الاصطناعي",
      threatsSub: "تم حظر الديب فيك عند البوابة",
      accuracyVector: "متجه الدقة",
      accuracySub: "ثقة جنائية مضبوطة بدقة",
      enterpriseCovered: "المؤسسات المؤمنة",
      enterpriseSub: "الحكومات وسجلات البنوك",
    },
    scanModal: {
      decentralized: "محرك الفحص اللامركزي لـ AIVERSE",
      title: "مساحة عمل تشخيص الثقة الآمنة",
      subtitle: "استيعاب حمولة الحماية الآمنة. الصق عناوين URL الاجتماعية أو نصوص البريد الإلكتروني أو تجزئة الملفات لمراجعة تقارير الموثوقية.",
      imgBtn: "📸 صورة (.jpg)",
      voiceBtn: "🎙️ تحليل الصوت",
      videoBtn: "🎥 ديب فيك فيديو",
      emailBtn: "📩 بريد احتيالي",
      inputParams: "معلمات إدخال الحمولة",
      secureActive: "النفق الآمن نشط",
      dragDrop: "اسحب وأسقط الملف أو تصفح السجلات لديه",
      dragSub: "يدعم PDF, WAV, PNG, MP4. سجلات خاصة مشفرة SOC2.",
      ingestBtn: "تحليل واستيعاب الحمولة بأمان",
      stage1: "المرحلة 1/2: فحص لِحامات البكسل",
      stage2: "المرحلة 2/2: حساب اتساق التوقيع",
      criticalTitle: "تشخيص حرج للغاية",
      authScore: "درجة الموثوقية",
      lowScore: "(منخفض)",
      classification: "التصنيف",
      legalAdmissible: "مقبول قانونياً",
      certificate: "شهادة تتبع تم التحقق منها",
      outputTitle: "مخرجات التحليل الجنائي للذكاء الاصطناعي:",
      outputMsg: "عدم تطابق في شبكة GAN. لا يتطابق ضغط الصوت الصوتي مع ملف الصوت البشري المادي. تم تسجيل الإجراءات الأمنية في السجل الكلي.",
      ingestNext: "استيعاب العينة التالية",
      closeWorkspace: "إغلاق مساحة العمل"
    },
    threats: {
      category: "القسم 02 // مخاطر المولدات",
      title: "نموذج تهديدات الذكاء الاصطناعي",
      subtitle: "تصل المواد الاصطناعية إلى مستوى الدقة البشرية. راجع نواقل الهجوم الرئيسية المستخدمة حالياً.",
      reconnaissance: "AIVERSE استطلاع التهديدات",
      activeInspect: "فحص نشط",
      inactiveInspect: "ناقل الفحص",
      deepNoiseMatch: "تطابق الضوضاء العميقة للصورة:",
      latentArtifacts: "العيوب الكامنة المشتبه بها",
      dragSlider: "اسحب في المعاينة للفحص",
      ganArtifacts: "تم العثور على أخطاء في واجهة GAN",
      pixelInconsistencies: "عدم اتساق في شبكة البكسل حول الحواف الجلدية",
      cleanOriginal: "البيانات الوصفية الأصلية النظيفة",
      verifiedRaw: "سجل مستشعر الكاميرا الخام الذي تم التحقق منه سليم",
    },
    workflow: {
      category: "القسم 03 // التدفق الجنائي للبيانات",
      title: "كيف يعمل AiVerse",
      subtitle: "يقوم الفاحص المتوازي متعدد النماذج بفك شفرة الحمض النووي الرقمي طبقة تلو الأخرى. تابع تسلسل المعالجة في الوقت الفعلي.",
      auditEngine: "محرك تدقيق AIVERSE v4.21",
      sandboxTitle: "بيئة فحص جنائي تفاعلية",
      sandboxSub: "حدد عينة من الأصول الرقمية أدناه لتشغيل الفحص الفعلي. شاهد كيف تنتشر الخوارزميات.",
      scanRunning: "الفحص الجنائي قيد التشغيل",
      resetEcosystem: "إعادة تعيين النظام",
      secureIngest: "برمجة واستيعاب آمن",
      consoleTitle: "لوحة تحكم حماية الفحص الفوري",
      consoleSub: "الوقت الفعلي: 2026-06-06 UTC",
      terminalIdleSubtitle: "حدد عينة وانقر فوق \"برمجة واستيعاب آمن\" لبدء اختبارات الثقة المتوازية.",
      processingStage: "[مرحلة المعالجة ... بدء أنماط التجزئة العصبية]"
    },
    modules: {
      category: "القسم 04 // عرض المنتجات",
      title: "وحدات المنصة",
      subtitle: "حلول ثقة سيادية مصممة لحماية هويات الشركات، الاتصالات والمحتوى الرقمي.",
      kpiLabel: "مؤشر الأداء الرئيسي",
    },
    demo: {
      category: "القسم 05-13 // مختبر التشخيص",
      title: "مركز تشخيص تفاعلي",
      subtitle: "قم بمحاكاة الكشف عن الديب فيك، ومخططات الطيف الصوتي، وفلاتر الأمن السيبراني.",
      orgsCovered: "المؤسسات المشمولة",
      orgsVal: "4,800 مؤسسة",
    },
    ecosystem: {
      nodeSelected: "العقدة المحددة حالياً: ",
      brainTitle: "AiVerse ONE",
      brainSub: "العقل الموحد",
    },
    metrics: {
      category: "سجلات التدقيق الناجحة",
      caseStudies: "تقييم الأداء المستمر",
      caseSubtitle: "نقوم بتقييم نماذجنا المتوازية يومياً وفقاً لأعلى المعايير الجنائية الدولية.",
      avgAccuracy: "98.7% متوسط الدقة",
      avgAccuracyTag: "دقة البكسل",
      latentDelay: "تأخير الاستجابة K",
      restartBtn: "إعادة تشغيل المحاكاة",
    },
    footer: {
      brandDesc: "جعل الذكاء الاصطناعي مسؤولاً وقابلاً للتتبع وجديراً بالثقة. منصة الحوكمة الفائقة المعتمدة من قبل البنوك المركزية والحكومات والعلامات التجارية العالمية.",
      contactEmail: "governance@aiverse.com",
      contactPhone: "+1 (800) 902-TRUST",
      contactAddr: "المدينة القديمة، زيورخ، سويسرا",
      endpointLease: "تأجير نقطة وصول آمنة",
      products: "المنتجات",
      solutions: "الحلول",
      company: "الشركة",
      contactHeader: "مكتب الاتصال",
    }
  }
};

const LanguageContext = createContext<{
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: typeof translations.en;
} | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem("aiverse_lang");
    if (saved && (saved === "en" || saved === "de" || saved === "fr" || saved === "es" || saved === "ja" || saved === "ml" || saved === "hi" || saved === "ar")) {
      return saved as LanguageCode;
    }
    return "en";
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("aiverse_lang", lang);
    // Dispatch a custom event so other listening modules update instantly
    window.dispatchEvent(new CustomEvent("aiverse_language_changed", { detail: lang }));
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return ctx;
};
